name: Проверка
on: [push]
jobs:
  tests:
    name: Тесты
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Установка Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6
    - name: Установка зависимостей
      run: |
        python -m pip install --upgrade pip
        pip install fastapi httpx requests
    - name: Pytest
      run: python3 tests.py
